export const settings = {
  simulation: { step: 1 / 120, maxSteps: 8 },
  movement: {
    baseSpeed: 6,
    groundAcceleration: 30,
    braking: 20,
    excessBraking: 10,
    landingSpeedResetDuration: 0.5,
    groundTurnBonus: 1.5,
    fullBonusTurnRate: 1.5,
    airTurnAcceleration: 3,
    airSteeringRate: 2,
    airAcceleration: 6,
    gravity: 20,
    jumpSpeed: 8,
    jumpBuffer: 0.1,
    radius: 0.35,
    height: 1.8,
  },
  camera: { eyeHeight: 1.65, fov: 85, sensitivity: 0.002, pitchLimit: Math.PI / 2 - 0.02 },
  weapons: {
    eyeHeight: 1.1,
    pitchDifference: 0.01,
    rocketSpeed: 40,
    rocketRadius: 0.08,
    rocketLifetime: 5,
    muzzleOffset: 0.4,
    cooldown: 0.4,
    blastRadius: 5,
    blastDamage: 30,
    blastImpulse: 16,
    explosionDuration: 0.45,
  },
  health: { max: 100, regeneration: 5, damageFlashDuration: 0.35 },
  world: { respawnHeight: -30 },
  training: { size: 160, wallHeight: 32, gridSpacing: 4 },
  checkpointTimer: {
    initial: 15,
    threshold: 10,
    largeDecrease: 0.5,
    smallDecrease: 0.25,
    minimum: 0,
  },
  corridor: {
    length: 48,
    width: 16,
    height: 24,
    elevationChance: 0.2,
    elevationFraction: 0.7,
    elevationAngleDegrees: 45,
    ahead: 6,
    behind: 2,
    checkpointInterval: 3,
    checkpointOffset: 8,
    fallingHeight: -2,
    deathHeight: -8,
    rebaseDistance: 1024,
  },
  ramps: {
    takeoffSpeedThreshold: 8,
  },
  audio: {
    volume: 0.5,
    files: {
      jump: '/assets/audio/jump.mp3',
      jump2: '/assets/audio/jump2.mp3',
      fire: '/assets/audio/rocket_fire.mp3',
      explosion: '/assets/audio/rocket-explosion.mp3',
      respawn: '/assets/audio/respawn.mp3',
      prepare: '/assets/audio/prepare.mp3',
      falling: '/assets/audio/falling.mp3',
      timerEnd: '/assets/audio/timer_end.mp3',
    },
    gains: {
      jump: 1,
      jump2: 1,
      fire: 1,
      explosion: 1,
      respawn: 1,
      prepare: 1,
      falling: 1,
      timerEnd: 1,
    },
    spatial: { refDistance: 3, maxDistance: 100, rolloffFactor: 1 },
  },
  keys: {
    forward: 'KeyW',
    backward: 'KeyS',
    left: 'KeyA',
    right: 'KeyD',
    jump: 'Space',
    reset: 'KeyR',
  },
} as const;

export type MovementConfig = { [K in keyof typeof settings.movement]: number };
